#!/bin/bash
LK1=$1
LKS=$@
DATE=$(date +%Y%m%d)

cat semkol_20120203.csv | head -n1 \
 | ./cutKV.sh > "lk/wk_${LK1}.csv"

for LK in $LKS; do
  ./filterkreis.sh "${LK}" >> "lk/wk_${LK1}.csv"
done

csv2ods -d";" --encoding=utf-8 -i "lk/wk_${LK1}.csv" -o "lk/lk_${LK1}_${DATE}.ods"

